CREATE DATABASE IF NOT EXISTS national_rehab_registry;
USE national_rehab_registry;


CREATE TABLE IF NOT EXISTS Person (
    SSN INT NOT NULL PRIMARY KEY,
    Name VARCHAR(255),
    Phone_number VARCHAR(20),
    Postal_code VARCHAR(255),
    Address VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS TreatmentPlan (
    TID INT NOT NULL PRIMARY KEY,
    Dosage_level INT
);


CREATE TABLE IF NOT EXISTS Staff (
    SID INTEGER PRIMARY KEY,
    SSN INTEGER,
    SUPERVISOR_ID INTEGER,
    FOREIGN KEY (SSN) REFERENCES Person(SSN)
);


CREATE TABLE IF NOT EXISTS PatientMonitors (
    PID INTEGER PRIMARY KEY,
    TYPE_OF_ADDICTION VARCHAR(255),
    PROGRESS_OF_RECOVERY VARCHAR(255),
    SID INTEGER,
    TID INTEGER,
    FOREIGN KEY (SID) REFERENCES Staff(SID) ON DELETE CASCADE,
    FOREIGN KEY (TID) REFERENCES TreatmentPlan(TID) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS SpecialistResponsible (
    SID INTEGER,
    TID INTEGER,
    Role VARCHAR(20),
    PRIMARY KEY (SID, TID),
    FOREIGN KEY (TID) REFERENCES TreatmentPlan(TID) ON DELETE CASCADE,
    FOREIGN KEY (SID) REFERENCES Staff(SID) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS TreatmentPlanAssigned (
    PID INT NOT NULL,
    TID INT NOT NULL,
    DurationTreatment DATE,
    PRIMARY KEY (PID, TID),
    FOREIGN KEY (PID) REFERENCES PatientMonitors(PID) ON DELETE CASCADE,
    FOREIGN KEY (TID) REFERENCES TreatmentPlan(TID)
);


CREATE TABLE IF NOT EXISTS MedicationPrescribes (
    MID INT PRIMARY KEY,
    TID INT,
    MEDICATION_NAME VARCHAR(255),
    FOREIGN KEY (TID) REFERENCES TreatmentPlan(TID)
);


CREATE TABLE IF NOT EXISTS Supervises (
    CaretakerID INT,
    SupervisorID INT,
    PRIMARY KEY (CaretakerID, SupervisorID),
    FOREIGN KEY (SupervisorID) REFERENCES Staff(SID)
);
