CREATE TABLE Person ( 

SSN int NOT NULL PRIMARY KEY, 

Name varchar(255), 

Phone_number int, 

Postal_code varchar(255), 

Address varchar(255) 

); 

 

CREATE TABLE Staff ( 

SID INTEGER PRIMARY KEY, 

SSN INTEGER, 

SUPERVISOR_ID INTEGER, 

FOREIGN KEY(SSN) REFERENCES Person(SSN) 

); 

 

CREATE TABLE SpecialistResponsible ( 

SID INTEGER, 

TID INTEGER, 

Role VARCHAR(20), 

PRIMARY KEY(SID,TID), 

FOREIGN KEY(TID) REFERENCES TreatmentPlan(TID) ON DELETE CASCADE, 

FOREIGN KEY(SID) REFERENCES Staff(SID) ON DELETE CASCADE 

); 

 

CREATE TABLE TreatmentPlanAssigned ( 

PID int NOT NULL, FOREIGN KEY(PID) REFERENCES PatientMonitors(PID) ON DELETE CASCADE, 

TID int NOT NULL, FOREIGN KEY(TID) REFERENCES TreatmentPlan(TID) 

DurationTreatment Date, 

PRIMARY KEY(PID,TID)); 

 

CREATE TABLE PatientMonitors ( 

PID INTEGER PRIMARY KEY, 

TYPE_OF_ADDICTION Varchar(255), 

PROGRESS_OF_RECOVERY Varchar(255), 

SID INTEGER, FOREIGN KEY(SID) REFERENCES Staff(SID) ON DELETE CASCADE, 

TID INTEGER, FOREIGN KEY(TID) REFERENCES TreatmentPlan(TID) ON DELETE CASCADE 

); 
