--PROJECTION QUERY
SELECT NAME  
FROM PERSON 
WHERE ADDRESS LIKE '%Shimmer St%'; 



--SELECT QUERY
SELECT *  
FROM PATIENTMONITORS  
WHERE TYPE_OF_ADDICTION LIKE '%Cannabis%'; 


--DIVISION QUERY
SELECT ROLE FROM SPECIALISTRESPONSIBLE  
WHERE TID IN (SELECT TID FROM TREATMENTPLAN WHERE DOSAGE_LEVEL > 2999);



--JOIN QUERY
SELECT p.NAME, s.SID  
FROM PERSON p, STAFF s 
WHERE p.SSN = s.SSN;


-- AGGREGATION QUERY
SELECT COUNT(*)  
FROM TREATMENTPLANASSIGNED 
WHERE DURATIONTREATMENT >= '2026-01-01' AND DURATIONTREATMENT <= '2026-12-31';


-- NESTED AGGREGATION WITH GROUP BY
SELECT MAX(DURATIONTREATMENT) FROM TREATMENTPLANASSIGNED;


-- DELETE QUERY
DELETE PATIENTMONITORS, TREATMENTPLANASSIGNED 
FROM PATIENTMONITORS 
JOIN TREATMENTPLANASSIGNED 
ON PATIENTMONITORS.PID = TREATMENTPLANASSIGNED.PID WHERE TREATMENTPLANASSIGNED.DURATIONTREATMENT < CURDATE(); 


-- UPDATE QUERY
UPDATE PATIENTMONITORS  
SET PROGRESS_OF_RECOVERY = 'Behavioral therapy no longer required' 
WHERE PID=8005