--PROJECTION QUERY
SELECT NAME  
FROM PERSON 
WHERE ADDRESS LIKE '%Shimmer St%'; 



--SELECT QUERY
SELECT *  
FROM PATIENTMONITORS  
WHERE TYPE_OF_ADDICTION LIKE '%Cannabis%'; 


--DIVISION QUERY
SELECT ROLE FROM SPECIALISTRESPONSIBLE  
WHERE TID IN (SELECT TID FROM TREATMENTPLAN WHERE DOSAGE_LEVEL > 2999);



--JOIN QUERY
SELECT p.NAME, s.SID  
FROM PERSON p, STAFF s 
WHERE p.SSN = s.SSN;


-- AGGREGATION QUERY COUNT
SELECT COUNT(*)  
FROM TREATMENTPLANASSIGNED 
WHERE DURATIONTREATMENT >= '2026-01-01' AND DURATIONTREATMENT <= '2026-12-31';

--AGGREGATION QUERY MAX
SELECT MAX(DURATIONTREATMENT) FROM TREATMENTPLANASSIGNED;

-- NESTED AGGREGATION WITH GROUP BY
SELECT p.TYPE_OF_ADDICTION
FROM TREATMENTPLANASSIGNED t
JOIN PATIENTMONITORS p ON t.PID = p.PID
WHERE t.DURATIONTREATMENT > CURDATE()
AND DATEDIFF(t.DURATIONTREATMENT, CURDATE()) > (
    SELECT AVG(DATEDIFF(DURATIONTREATMENT, CURDATE()))
    FROM TREATMENTPLANASSIGNED
    WHERE DURATIONTREATMENT > CURDATE()
)
GROUP BY p.TYPE_OF_ADDICTION;


-- DELETE QUERY
DELETE PATIENTMONITORS, TREATMENTPLANASSIGNED 
FROM PATIENTMONITORS 
JOIN TREATMENTPLANASSIGNED 
ON PATIENTMONITORS.PID = TREATMENTPLANASSIGNED.PID WHERE TREATMENTPLANASSIGNED.DURATIONTREATMENT < CURDATE(); 


-- UPDATE QUERY
UPDATE PATIENTMONITORS  
SET PROGRESS_OF_RECOVERY = 'Behavioral therapy no longer required' 
WHERE PID=8005